### ISSUE TITLE
Something confused about the max_nodes_per_batch parameters

### ISSUE THREAD

**Issue by bywbilly** [dselsam/neurosat#4]
I find that in the toy examples, you set this hyper-parameter as 60000, however, in the paper, you set this as 12000, which is smaller than 60000.

From my understanding, more nodes mean more expressive representation. I am wondering if my understanding correct? And why you set this hyper-parameter in the toy examples.

Thanks!

**Comment by dselsam** [comment]
I don't remember but probably just because the toy problems are smaller. I generally just set it to fill GPU memory.
