### ISSUE TITLE
Can't get normal result and I am confused.

### ISSUE THREAD

**Issue by qunqunqun** [dselsam/neurosat#5]
Sorry for interrupting you when you are busy with working, I'm trying to modify this network to do some experiment, however I can't get normal result. I haven changed the size of problem by modify gen_data.py,but the result are as the same. For example, the loss are always 0.6931 and the matrix are always 50% accuracy. I wonder how can I get some normal result!

Training
Loading data/train/sr5/data_dir=grp1_npb=60000_nb=8.pkl...
[0] 0.6932 (0.30, 0.20, 0.30, 0.20) [42s]
Start Trian
Loading data/train/sr5/data_dir=grp2_npb=60000_nb=10.pkl...
[1] 0.6932 (0.25, 0.25, 0.25, 0.25) [43s]
Start Trian
Loading data/train/sr5/data_dir=grp3_npb=60000_nb=6.pkl...
[2] 0.6932 (0.20, 0.30, 0.20, 0.30) [43s]
Start Trian
Loading data/train/sr5/data_dir=grp8_npb=60000_nb=7.pkl...
[3] 0.6932 (0.30, 0.20, 0.30, 0.20) [53s]
Start Trian
Loading data/train/sr5/data_dir=grp9_npb=60000_nb=7.pkl...
[4] 0.6932 (0.20, 0.30, 0.20, 0.30) [44s]

Test:
data/test/sr5/data_dir=grp8_npb=60000_nb=9.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp2_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp10_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp5_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp1_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp9_npb=60000_nb=10.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp3_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp6_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp4_npb=60000_nb=8.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)
data/test/sr5/data_dir=grp7_npb=60000_nb=9.pkl 0.6932 (0.50, 0.00, 0.50, 0.00)

**Comment by dselsam** [comment]
You are running a toy model on toy data. It takes some system engineering to reproduce the qualitative behavior of NeuroSAT, and we do not provide push-button support. See also https://github.com/dselsam/neurosat/issues/2#issuecomment-379064957
