### ISSUE TITLE
Procedure to generate `different problems` in NeuroSAT

### ISSUE THREAD

**Issue by lee-man** [dselsam/neurosat#7]
Hi,

Is there any script which can illustrate the procedure to generate `different problems`, such as `six different random graph distributions` and `graph coloring problems (3 ≤ k ≤ 5), dominating-set problems (2 ≤ k ≤ 4)), clique-detection problems (3 ≤ k ≤ 5), and vertex cover problems (4 ≤ k ≤ 6).`

Thanks!

**Comment by dselsam** [comment]
Unfortunately, this script has not survived, but it was only a few lines on top of [CNFGen](https://massimolauria.net/cnfgen/https://massimolauria.net/cnfgen/) and the details are in the paper.
